spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
